# Generated by Django 4.2.4 on 2023-08-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True),
        ),
    ]
